[build]
  # Directory con i file sorgente
  base = "."
  
  # Comando per il build
  command = "npm run build"
  
  # Directory con i file compilati
  publish = "dist"   # ✅ Corretto (Vite genera in dist)

[build.environment]
  # Versione Node.js
  NODE_VERSION = "18"
  
  # Cache delle dipendenze npm
  NPM_FLAGS = "--prefer-offline --no-audit"

# Redirects e rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers di sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://app.supabase.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

# Cache statico per assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache per il service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Ottimizzazioni per le performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin Netlify (opzionali)
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Funzioni Netlify (se necessarie)
[functions]
  directory = "netlify/functions"

# Split testing (opzionale)
# [context.branch-deploy]
#   command = "npm run build:staging"

# Variabili d'ambiente per diversi contesti
[context.production.environment]
  REACT_APP_ENV = "production"
  REACT_APP_DEBUG_MODE = "false"

[context.deploy-preview.environment]
  REACT_APP_ENV = "preview"
  REACT_APP_DEBUG_MODE = "true"

[context.branch-deploy.environment]
  REACT_APP_ENV = "development"
  REACT_APP_DEBUG_MODE = "true"